In [4]:
import pandas as pd
from collections import Counter

In [6]:
data = pd.read_csv('data/PoPCites2.csv');

In [4]:
data

,Cites,Authors,Title,Year,Source,Publisher,ArticleURL,CitesURL,GSRank,QueryDate,...,Volume,Issue,StartPage,EndPage,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,Age,Abstract
0,435,R Mall,Fundamentals of software engineering,2018,NaN,books.google.com,https://books.google.com/books?hl=en&lr=&id=-J...,https://scholar.google.com/scholar?cites=22762...,1,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,435,145.00,435,1,3,"This new edition of the book, is restructured ..."
1,1226,"M Brambilla, J Cabot, M Wimmer",Model-driven software engineering in practice,2017,… on software engineering,morganclaypool.com,https://www.morganclaypool.com/doi/abs/10.2200...,https://scholar.google.com/scholar?cites=47960...,2,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,1226,306.50,409,3,4,This book discusses how model-based approaches...
2,118,"C Page, HW Six",Software Engineering,2017,Larsen and Keller Education,repo.mimitlibrary.ac.in,http://repo.mimitlibrary.ac.in:8080/jspui/bits...,https://scholar.google.com/scholar?cites=15367...,3,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,118,29.50,59,2,4,1. a) What are drawbacks of Spiral Model? b) W...
3,22,G Booch,The history of software engineering,2018,IEEE Software,ieeexplore.ieee.org,https://ieeexplore.ieee.org/abstract/document/...,https://scholar.google.com/scholar?cites=16004...,4,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,22,7.33,22,1,3,"Grady Booch, one of UML's original authors, of..."
4,142,"B Kitchenham, L Madeyski, D Budgen, J Keung…",Robust statistical methods for empirical softw...,2017,… Software Engineering,Springer,https://link.springer.com/article/10.1007/s106...,https://scholar.google.com/scholar?cites=16050...,5,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,142,35.50,28,5,4,There have been many changes in statistical th...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,18,"V Garousi, M Felderer",Experience-based guidelines for effective and ...,2017,… and Assessment in Software Engineering,dl.acm.org,https://dl.acm.org/doi/abs/10.1145/3084226.308...,https://scholar.google.com/scholar?cites=11972...,196,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,18,4.50,9,2,4,To systematically collect evidence and to stru...
196,17,"N Tavares de Sousa, W Hasselbring, T Weber…",Designing a generic research data infrastructu...,2018,NaN,oceanrep.geomar.de,http://oceanrep.geomar.de/id/eprint/42215,https://scholar.google.com/scholar?cites=71098...,197,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,17,5.67,4,4,3,Long-living software systems undergo a continu...
197,13,"S Krusche, N von Frankenberg, S Afifi",Experiences of a Software Engineering Course b...,2017,SEUH,in.tum.de,https://www1.in.tum.de/lehrstuhl_1/research/pa...,https://scholar.google.com/scholar?cites=28053...,198,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,13,3.25,4,3,4,Learning to apply software engineering require...
198,16,"H Erdogmus, C Péraire",Flipping a graduate-level software engineering...,2017,… Engineering: Software Engineering …,ieeexplore.ieee.org,https://ieeexplore.ieee.org/abstract/document/...,https://scholar.google.com/scholar?cites=49153...,199,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,16,4.00,8,2,4,Creating a graduate-level software engineering...
199,6,"K Meinke, A Bennaceur",Machine learning for software engineering: mod...,2018,… Conference on Software Engineering …,ieeexplore.ieee.org,https://ieeexplore.ieee.org/abstract/document/...,https://scholar.google.com/scholar?cites=17771...,200,2021-04-19 20:05:26,...,NaN,NaN,NaN,NaN,6,2.00,3,2,3,Machine Learning (ML) is the discipline that s...

In [5]:
data['Authors']

0                                            R Mall
1                    M Brambilla, J Cabot, M Wimmer
2                                    C Page, HW Six
3                                           G Booch
4      B Kitchenham, L Madeyski, D Budgen, J Keung…
                           ...
195                           V Garousi, M Felderer
196     N Tavares de Sousa, W Hasselbring, T Weber…
197           S Krusche, N von Frankenberg, S Afifi
198                           H Erdogmus, C Péraire
199                           K Meinke, A Bennaceur
Name: Authors, Length: 200, dtype: object

In [7]:
list = data['Authors'].str.split(',', expand = True)

In [10]:
list

                      0                   1          2          3     4
0                R Mall                None       None       None  None
1           M Brambilla             J Cabot   M Wimmer       None  None
2                C Page              HW Six       None       None  None
3               G Booch                None       None       None  None
4          B Kitchenham          L Madeyski   D Budgen   J Keung…  None
..                  ...                 ...        ...        ...   ...
195           V Garousi          M Felderer       None       None  None
196  N Tavares de Sousa       W Hasselbring   T Weber…       None  None
197           S Krusche   N von Frankenberg    S Afifi       None  None
198          H Erdogmus           C Péraire       None       None  None
199            K Meinke         A Bennaceur       None       None  None

[200 rows x 5 columns]

In [11]:
testdat

NameError: name 'testdata' is not defined

In [12]:
test_data = pd.read_csv('data/PoPCites.csv');

In [9]:
test_list = test_data['city']

KeyError: 'city'

In [111]:
print([item for item, count in Counter(test_list).items() if count > 1])

['New Orleans', 'Bridgeport', 'Anchorage', 'Chicago', 'San Jose', 'Baltimore', 'Los Angeles', 'Phoenix', 'Milwaukee', 'Irving', 'Albany', 'New York', 'Conroe', 'San Antonio', 'Abilene', 'Fairbanks', 'Miami', 'Boston', 'Madison', 'Philadelphia', 'Tullahoma', 'Columbia', 'Providence', 'Monroe Township', 'Austin', 'Erie', 'Boise', 'San Francisco', 'Concord', 'Newark', 'Jacksonville', 'Hayward', 'Gardena', 'Waco', 'San Leandro', 'Indianapolis', 'Mc Lean', 'Honolulu', 'Burnsville', 'Portland', 'Worcester', 'Mesquite', 'Thousand Oaks', 'Denver', 'Dallas', 'Nashville', 'Beverly Hills', 'Atlantic City', 'Cincinnati', 'Cherry Hill', 'Garden City', 'Round Rock', 'Jersey City', 'Bridgewater', 'Riverton', 'Bangor', 'Lafayette', 'Orlando', 'Escondido', 'New Haven', 'Toledo', 'Roseville', 'Tampa', 'El Cajon', 'Brooklyn', 'Saint Louis', 'Seattle', 'Burlington', 'Richmond', 'Scottsdale', 'La Mesa', 'Atlanta', 'Cleveland', 'Colorado Springs', 'Greensboro', 'Memphis', 'Richland', 'Kearny', 'Englewood', 'San Diego']

In [116]:
test_list

0              New Orleans
1                 Brighton
2               Bridgeport
3                Anchorage
4                 Hamilton
5                  Ashland
6                  Chicago
7                 San Jose
8              Sioux Falls
9                Baltimore
10              Kulpsville
11           Middle Island
12             Los Angeles
13           Chagrin Falls
14                  Laredo
15                 Phoenix
16            Mc Minnville
17               Milwaukee
18                  Taylor
19                Rockford
20                   Aston
21                San Jose
22                  Irving
23                  Albany
24               Middlesex
25           Stevens Point
26                 Shawnee
27                  Easton
28                New York
29                  Conroe
30                Columbus
31              Las Cruces
32         Ridgefield Park
33                Dunellen
34                New York
35                Metairie
36                New York
37               Camarillo
38             San Antonio
39                 Abilene
40              Prineville
41           Overland Park
42               Fairbanks
43                   Miami
44               Fairbanks
45                 Hopkins
46                  Boston
47             Los Angeles
48                 Madison
49            Philadelphia
50                New York
51               Tullahoma
52                Columbia
53                   Wayne
54              Flemington
55                Westbury
56              Jenkintown
57                Van Nuys
58              Providence
59       Huntingdon Valley
60              Providence
61         Monroe Township
62                  Austin
63               Littleton
64               Milwaukee
65                New York
66               Anchorage
67                    Erie
68             Glen Burnie
69                   Boise
70           San Francisco
71             Chapel Hill
72              San Carlos
73                 Concord
74                  London
75              Wellsville
76               Baltimore
77                  Newark
78                 Chicago
79                  Newark
80                  Clovis
81           Staten Island
82            Jacksonville
83                 Hayward
84               Beachwood
85                  Euless
86                 Gardena
87                Evanston
88                   Akron
89            Philadelphia
90              Burlingame
91             San Gabriel
92                    Waco
93               Anchorage
94                San Jose
95             San Leandro
96            Indianapolis
97            Rock Springs
98                 Mc Lean
99             New Orleans
100                Boulder
101            San Leandro
102               Honolulu
103             Burnsville
104             High Point
105               Lynbrook
106               Portland
107                 Beloit
108              Worcester
109                  Miami
110                   Erie
111               Mesquite
112              Tullahoma
113               Paterson
114              Homestead
115           Owings Mills
116          Thousand Oaks
117               Honolulu
118                 Albany
119                 Boston
120             Hackensack
121              San Mateo
122                Ontario
123                Oakland
124                   Troy
125          Clarks Summit
126                 Orange
127              Pittstown
128                  Cocoa
129                  Bronx
130             Pearl City
131                 Denver
132               Rockaway
133                Absecon
134             Plainfield
135             Middleboro
136                Chicago
137               Portland
138                 Dallas
139                Chicago
140                Findlay
141              Riverside
142                   Waco
143              Nashville
144              Milwaukee
145                Preston
146                 Irving
147          Beverly Hills
148             Massapequa
149          Atlantic City
150             Cincinnati
151                 Eugene
152             Smithfield
153               New York
154                Phoenix
155           Indianapolis
156               Syracuse
157            Cherry Hill
158            Garden City
159            Little Rock
160             Saint Paul
161           Philadelphia
162                  Houma
163             Ronkonkoma
164             Sacramento
165                  Boise
166             Round Rock
167           Philadelphia
168                   Hilo
169                   Reno
170               Wheeling
171               Randolph
172            Spartanburg
173              Hampstead
174           Mount Vernon
175               New York
176               Berkeley
177                Concord
178          San Francisco
179                Paramus
180                 Oakley
181                Chicago
182            Cedar Grove
183             Perrysburg
184                Gardena
185              Homosassa
186            Santa Clara
187               Hazleton
188            Jersey City
189              San Ramon
190            Bridgewater
191                Bohemia
192          Thousand Oaks
193             Somerville
194              Beaverton
195                  Salem
196               Riverton
197           Douglasville
198           Jacksonville
199                 Bangor
200              Kennedale
201                Buffalo
202              Opa Locka
203               New York
204           Philadelphia
205              Crestview
206          San Francisco
207               San Jose
208    South San Francisco
209             Northridge
210           Philadelphia
211              Lafayette
212               Dearborn
213                 Austin
214                 Dallas
215                 Vashon
216            Coatesville
217           Philadelphia
218                Gardena
219           Rohnert Park
220                Orlando
221              Escondido
222            Westborough
223                 Conroe
224              Milwaukee
225               El Monte
226                Yonkers
227                 Dallas
228                 Biloxi
229                  Miami
230               New York
231                 Ramsey
232              Ann Arbor
233              Deer Park
234                 Canton
235              New Haven
236                Fairfax
237             Wilmington
238                 Toledo
239                 Tacoma
240              Roseville
241               Riverton
242                 Warren
243               Richboro
244                  Tampa
245               El Cajon
246        College Station
247          Highland Park
248          Atlantic City
249            Bridgewater
250               Brooklyn
251            Saint Louis
252               Stockton
253           Little Falls
254           Indianapolis
255                Seattle
256             Burlington
257                   Hays
258                Orlando
259            Minneapolis
260               Columbia
261             Santa Rosa
262               Palatine
263             Costa Mesa
264                 Denver
265              New Haven
266                Bothell
267           Strongsville
268               Plaistow
269        Satellite Beach
270               New York
271       Huntington Beach
272             Southfield
273           Indianapolis
274          Wichita Falls
275            North Haven
276               Aberdeen
277            New Orleans
278               Richmond
279            Southampton
280               Shakopee
281                  Miami
282              Milwaukee
283               Somerset
284                  Fargo
285            Carson City
286             Scottsdale
287              Nashville
288              Salisbury
289               New York
290               Amarillo
291            Los Angeles
292                La Mesa
293                Atlanta
294              Worcester
295                  Niles
296              Fairfield
297              Lafayette
298                 Denver
299            Valley Park
300              Arlington
301                  Tampa
302                Atlanta
303         Cathedral City
304                Lansing
305                Phoenix
306                 Bangor
307                Clinton
308                   York
309               Mesquite
310                  Butte
311             Livingston
312              Waterford
313              Cleveland
314                Abilene
315             Fort Worth
316               Brooklyn
317             Providence
318              Lancaster
319               Johnston
320                Hialeah
321            Jersey City
322            San Antonio
323               Brooklyn
324                 Pomona
325              Cleveland
326               New York
327               Richmond
328                  Trion
329              Broussard
330                 Nutley
331                 Vestal
332                Passaic
333                 Moscow
334          San Francisco
335        North Attleboro
336              Rochester
337              Green Bay
338              Baltimore
339       Colorado Springs
340                 Toledo
341            Hyattsville
342            New Bedford
343                Mc Lean
344                Hanover
345                 Austin
346                 Peoria
347                Bucyrus
348                   Kent
349             Cincinnati
350            Bloomington
351      Arlington Heights
352               Brooklyn
353                Orlando
354          Beverly Hills
355                Brandon
356                El Paso
357               El Cajon
358            Bladensburg
359                Anaheim
360            Saint Louis
361             Round Rock
362             Greensboro
363                  Coram
364              Lyndhurst
365                Memphis
366                Atlanta
367               Pacifica
368             Burnsville
369             Scottsdale
370       Long Island City
371                Atlanta
372             Northfield
373                Norwalk
374             Fort Wayne
375               Meridian
376       Sterling Heights
377       Colorado Springs
378               New York
379                Hayward
380                Chicago
381               Scranton
382               Oroville
383            Port Jervis
384             Brook Park
385             Bloomfield
386              Anchorage
387           Philadelphia
388             Cincinnati
389                Gardena
390             Des Moines
391        King of Prussia
392                Raleigh
393               Richland
394                 Pelham
395              Parkville
396             Hicksville
397              Worcester
398                  Tulsa
399               Muskegon
400              Lafayette
401          Bowling Green
402                La Mesa
403             Bridgeport
404                 Kearny
405              Barberton
406              Englewood
407           Grand Rapids
408                  Pearl
409                Memphis
410              Englewood
411                Memphis
412               Pasadena
413                Chicago
414                Astoria
415               Richland
416              Baltimore
417                 Newark
418             Bellflower
419             Toms River
420               Denville
421                 Denver
422           Newport News
423                Phoenix
424                  Miami
425                Phoenix
426               Oak Hill
427          San Francisco
428              San Diego
429            Jersey City
430         San Bernardino
431              Cambridge
432              Escondido
433                Gardena
434             Harrisburg
435                   Mesa
436             Lake Worth
437              Nashville
438             Burlington
439                  Milan
440                 Conroe
441                Clifton
442             Union City
443                  Miami
444                   Moss
445              Santa Ana
446        Rolling Meadows
447               Hatfield
448               Whippany
449                   Erie
450         Salt Lake City
451           Fayetteville
452            Los Angeles
453           East Lansing
454                  Utica
455             South Bend
456                Orlando
457               Harrison
458                Trenton
459                Madison
460                Katonah
461             Greensboro
462              Baltimore
463        Monroe Township
464              Kerrville
465      Elk Grove Village
466               Freehold
467                  Omaha
468              Annandale
469                  Plano
470               New York
471                Syosset
472          Crystal River
473              Fortville
474           Saint Joseph
475                Jackson
476                Abilene
477               Saratoga
478            Cherry Hill
479                Hayward
480               Longwood
481               Cheyenne
482            Garden City
483                Madison
484                 Kearny
485              Old Forge
486              San Diego
487         Thousand Palms
488           Margate City
489             Providence
490                Abilene
491              Roseville
492          Daytona Beach
493             Washington
494                 Novato
495                  Boise
496                Elkhart
497               Alliance
498                Seattle
499                Orlando
Name: city, dtype: object

In [2]:
for city in test_list:
    print(city)

NameError: name 'test_list' is not defined